ris-99 Implement Navigation V2 Component
risedle/interface pull request #216
Opened 2022-05-20 07:29 UTC by math-marcellino

1.  Setup Colors in Tailwind Config
2. Setup Text Styles in `global.css`
3. Implement `Navigation V2` Component
![image](https://user-images.githubusercontent.com/81855912/169476067-d57e8586-8a8e-4918-877c-eee7029b0280.png)
Note: The preview of this component can be seen in `Storybook`
![image](https://user-images.githubusercontent.com/81855912/169476334-88af7d66-f338-476a-981c-6ed76375ec4c.png)

2022-05-20 08:05 UTC, pyk requested changes

2022-05-20 08:05 UTC, pyk commented on modules/homePage/component/v2/Navigation.tsx
> +        <div className="flex-column flex items-center gap-[44px] py-[16px] px-[192px]">
use 

- `py-2` instead of `py-[16px]`
- `gap-11` instead of `gap-[44px]`

2022-05-20 08:05 UTC, pyk commented on modules/homePage/component/v2/Navigation.tsx
> +            <div className="flex flex-row items-start gap-[8px]">
gap-[8px] -> gap-2

2022-05-20 08:05 UTC, pyk commented on modules/homePage/component/v2/Navigation.tsx
> +                <div className="flex flex-row items-center gap-[90px] rounded-full bg-light-neutral-subtle/10 p-[8px] pl-[16px]">
p-[8px] pl-[16px]

replace with

p-2 & pl-4

2022-05-20 08:05 UTC, pyk commented on modules/homePage/component/v2/Navigation.tsx
> +                    <div className="flex flex-row items-center gap-[8px]">
gap-[8px] -> gap-2

2022-05-20 08:05 UTC, pyk commented on modules/homePage/component/v2/Navigation.tsx
> +                        </svg>
can we make this as assets instead?

2022-05-20 08:05 UTC, pyk commented on modules/homePage/component/v2/Navigation.tsx
> +                    <div className="flex flex-row items-start gap-[4px]">
gap-[4x] to gap-1

2022-05-20 08:05 UTC, pyk commented on modules/homePage/component/v2/Navigation.tsx
> +                        <div className="flex h-[24px] w-[24px] items-center justify-center gap-[10px] rounded-[8px] bg-dark-background-elevated p-[8px]">
```
gap-[10px] rounded-[8px] p-[8px]
```

replace with

```
gap-2.5 rounded-2 p-2
```

2022-05-20 08:05 UTC, pyk commented on modules/homePage/component/v2/Navigation.tsx
> +                        <div className="flex h-[24px] w-[24px] items-center justify-center gap-[10px] rounded-[8px] bg-dark-background-elevated p-[8px]">
```
h-[24px] w-[24px] gap-[10px] rounded-[8px] p-[8px]
```

replace with

```
h-6 w-6 gap-2.5 rounded-2 p-2
```

2022-05-20 08:05 UTC, pyk commented on styles/globals.css
> +        @apply font-inter text-[148px] font-extrabold leading-[136px] tracking-[-0.02em] text-black;
Use font size here https://tailwindcss.com/docs/font-size

2022-05-20 08:05 UTC, pyk commented on uikit/buttonV2/ButtonSecondary.tsx
> +            extraClass = "px-[16px] heading-h7";
```
px-[16px] -> p-4
```

2022-05-20 08:05 UTC, pyk commented on uikit/buttonV2/ButtonSecondary.tsx
> +            extraClass = "px-[20px] heading-h6";
Fix padding https://tailwindcss.com/docs/padding

2022-05-20 08:05 UTC, pyk commented on uikit/buttonV2/ButtonSecondary.tsx
> +            extraClass = "px-[24px] heading-h6";
same here https://tailwindcss.com/docs/padding

2022-05-20 08:05 UTC, pyk commented on uikit/layout/LogoV2.tsx
> +        <div className="flex h-[24px] w-[83px] flex-row items-center gap-[7px]">
use valid tailwind insted of `*-[xx px]`

2022-05-20 08:41 UTC, math-marcellino commented
Changed arbitrary values to default tailwind values. But there are some values that is not available from the default tailwind values, so arbitrary values are still used in some cases, for example:
- text-[148px]
- leading-[136px]
- px-[192px]
- etc

2022-05-20 09:33 UTC, pyk approved these changes

2022-05-20 09:33 UTC, pyk commented
LGTM, tyyy @math-marcellino

2022-05-20 14:10 UTC, math-marcellino commented
I think we can just display the svg with `img` tag for now, since the svgs is static in v2, where we only have dark mode design if I'm not mistaken, so we don't have to change the style following the theme. But is there any better way to handle these svgs?

cc: @pyk @asaadam

2022-05-21 11:28 UTC, asaadam commented
@math-marcellino to handle svg that can change color, it must be converted to component
since we don't need that, we can just use `img` for now.

LGTM 
Thaks @math-marcellino

2022-05-21 11:29 UTC, asaadam approved these changes

2022-05-21 11:29 UTC, merged