Fix Responsive Layout & Styling V2
risedle/interface pull request #227
Opened 2022-06-06 08:59 UTC by math-marcellino

## 1. Responsive Navigation
TODO: 
- Implement `opened` state of menu button in mobile layout

The `opened` state hasn't been provided in figma
cc: @ayikfour 

## 2. Implement Jumbotrons in Layout
NOTE:
- This PR also contains the `Third Jumbotron`, which actually is still WIP

TODO:
- Implement gradients in `Third Jumbotron`

## 3. Configure Typography and Font
Typography is implemented as classes in `globals.css`

2022-06-08 15:15 UTC, asaadam commented on modules/homePage/component/v2/SecondJumbotron/SecondJumbotron.tsx
> +        <div className="mx-auto max-w-[343px] pt-32 sm:max-w-[552px] lg:max-w-[936px] xl:max-w-[1128px]">
from where did you get this number? 
just courius

2022-06-08 15:15 UTC, asaadam approved these changes
LGTM!

2022-06-08 15:16 UTC, math-marcellino commented on modules/homePage/component/v2/SecondJumbotron/SecondJumbotron.tsx
> +        <div className="mx-auto max-w-[343px] pt-32 sm:max-w-[552px] lg:max-w-[936px] xl:max-w-[1128px]">
max width is defined in figma sir hehe. For example this one:
![image](https://user-images.githubusercontent.com/81855912/172653587-d9778177-f254-47a6-8a85-e12b2fcfb02b.png)

2022-06-08 15:17 UTC, asaadam requested changes
![image](https://user-images.githubusercontent.com/1397612/172653668-67311a13-b935-437a-8bef-cfd036236a57.png)

ups this section looks like not responsive

2022-06-08 15:20 UTC, math-marcellino commented
> ![image](https://user-images.githubusercontent.com/1397612/172653668-67311a13-b935-437a-8bef-cfd036236a57.png)
> 
> ups this section looks like not responsive

@asaadam  Hmm if we look at the design in figma, it was designed this way for the mobile version:
![image](https://user-images.githubusercontent.com/81855912/172654224-84a9aa80-6de7-42ca-acd0-5ad6efb5854f.png)

cc @ayikfour

2022-06-08 16:22 UTC, ayikfour commented
Guys sorry just read this up. I forgot to write the specs.

I've been thinking about using HTML Marquee to show the metrics endlessly on mobile

here's the prototype https://www.figma.com/proto/nfbswhv2r8e2g7e4OPAyBw/Website-2.0?node-id=447%3A5914&viewport=-952%2C-36%2C0.53&scaling=min-zoom&starting-point-node-id=997%3A17986&show-proto-sidebar=1

I know this is deprecated on some, but can we handle it with JS? or even still use it with the default HTML Marquee tag? https://www.w3schools.in/html/marquee-tag

2022-06-09 10:23 UTC, math-marcellino commented
> Guys sorry just read this up. I forgot to write the specs.
> 
> I've been thinking about using HTML Marquee to show the metrics endlessly on mobile
> 
> here's the prototype https://www.figma.com/proto/nfbswhv2r8e2g7e4OPAyBw/Website-2.0?node-id=447%3A5914&viewport=-952%2C-36%2C0.53&scaling=min-zoom&starting-point-node-id=997%3A17986&show-proto-sidebar=1
> 
> I know this is deprecated on some, but can we handle it with JS? or even still use it with the default HTML Marquee tag? https://www.w3schools.in/html/marquee-tag

I tried to use `marquee` HTML tag, but seems like it's not supported by JSX.
![image](https://user-images.githubusercontent.com/81855912/172825315-969ed252-02ee-45ae-80df-bb2f6222d0c0.png)

But I also find a `marquee` library for React: https://www.react-fast-marquee.com/
@asaadam wdyt? Can we use this?

cc @ayikfour

2022-06-09 10:45 UTC, ayikfour commented
let me know if its possible or not guys, if it's impacting bundle size I could provide the static one

2022-06-09 14:36 UTC, asaadam approved these changes

2022-06-09 14:39 UTC, merged